### PR TITLE
Upgrading training materials to Corda 4.0

### PR DESCRIPTION
**Pull request by rogersanick**

### CODE REVIEW

**Comment by amoothart** [comment]
I was not able to build the Corda4.0 branch locally. I've got a number of changes to add to the PR which I will submit shortly.

**Comment by amoothart** [comment]
@rogersanick before committing the following issues remain:
Java unit tests still do not pass due to a serialization error
Could not issue on IOU via API when running the nodes locally

**Comment by amoothart** [comment]
Also we should test that the java/kotlin modules issue in IntelliJ is not an issue for trainees.

**Comment by bennytanr3** [comment]
**For build.gradle in java:source**
`sourceSets {
    main {
        resources {
            srcDir "../config/dev"
        }
    }
    test {
        resources {
            srcDir "../config/test"
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDir file('src/test/java')
        }
    }
}`

**This is causing circular reference for the java unit tests**
compileClasspath += main.output + test.output
runtimeClasspath += main.output + test.output
srcDir file('src/test/java')

**Comment by bennytanr3** [comment]
On the cluttered workspace when you open the repo. I think we have to make call here because we are pushing the .idea folder with all the associated configurations, so you do need to clean up your workspace before you push the associated .idea workspace files. Without that, intellij will just generates a new one when we open the project. 

The downside is that the unit tests configuration be missing, but we can teach people how to invoke it by going to gradle-> kotlin-source/java-source -> Tasks ->verification -> test, which creates a new run configuration.

**Comment by bennytanr3** [comment]
Quick check on the Java src, are the following intentionally not implemented i.e. we are not putting in as a todo, correct?
API - transfer-iou, settle-iou and self-issue-cash.

**Comment by amoothart** [comment]
@bennytanr3 

Not sure I understand the circular reference issue. Can you expand on this?

The .idea files are removed in the Corda4.0 branch, we don't want those committed to IntelliJ because it will cause an issue with two root source directories sharing the same context. @rogersanick can you comment on including the run configurations without the .idea files?

Yes, transfer and settle are not included by design. There hasn't been any demand for them yet but if that's an issue we could certainly build them in.

**Comment by bennytanr3** [comment]
@amoothart Basically when you run the Java:source unit tests, it throws up an error on the gradle tasks
Screen Shot 2019-03-27 at 11 22 58 AM
:
FAILURE: Build failed with an exception.
* What went wrong:
Circular dependency between the following tasks:
\--- :java-source:testClasses
       \--- :java-source:compileTestJava (*)
(*) - details omitted (listed previously)
* Try:

**Comment by rogersanick** [comment]
Hey @amoothart and @bennytanr3 - I've updated the 4.0 branch with an additional parameter in the compiler.xml (which is now included in this repo). Everything is working for me now. Are you able to pull down and attempt to run the Java and Kotlin unit tests?

**Comment by amoothart** [comment]
@bennytanr3 we have run configs now and I deleted the circular dependency in the build.gradle so your issue should be resolved.

**Pull request merged**
